name: leancode_markup
version: 0.0.2
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_markup
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  Simple package that allows you parse text with predefined tags, and
  returns styled Flutter text.

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  logging: ^1.2.0
  meta: ^1.9.1
  petitparser: ^6.0.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  leancode_lint: ^12.0.0
