name: login_client
version: 1.1.2
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  OAuth2 compliant login client that stores credentials
  for the currently authenticated user and automatically
  refreshes tokens.

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  http_parser: ^3.1.4
  meta: ^1.2.4
  oauth2: ^1.6.3

dev_dependencies:
  lint: ^1.3.0
  mockito: ^4.1.3
  test: ^1.15.7
  test_coverage: ^0.5.0
