name: login_client
version: 3.2.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  OAuth2 compliant login client that stores credentials
  for the currently authenticated user and automatically
  refreshes tokens.

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  http: ^1.0.0
  http_parser: ^4.0.0
  meta: ^1.3.0
  oauth2: ^2.0.0

dev_dependencies:
  coverage: ^1.6.3
  custom_lint: ">=0.6.4 <0.8.0"
  leancode_lint: ">=12.0.0 <16.0.0"
  mocktail: ^1.0.1
  test: ^1.16.4
