name: leancode_markup
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  meta: ^1.9.1
  petitparser: ^6.0.1

dev_dependencies:
  benchmark_harness: ^2.2.2
  custom_lint: ^0.5.8
  flutter_test:
    sdk: flutter
  leancode_lint: ^7.0.0+1
