name: leancode_lint
version: 19.0.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_lint
repository: https://github.com/leancodepl/flutter_corelibrary
description: Robust, high-quality lint rules used at LeanCode.

topics:
  - analysis
  - lints

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  _fe_analyzer_shared: ^92.0.0
  analysis_server_plugin: ^0.3.4
  analyzer: ^9.0.0
  analyzer_plugin: ^0.13.11
  meta: ^1.17.0
  path: ^1.9.1
  source_span: ^1.10.1
  yaml: ^3.1.3

dev_dependencies:
  analyzer_testing: ^0.1.7
  test_reflective_loader: ^0.4.0
