name: leancode_lint
version: 6.0.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_lint
repository: https://github.com/leancodepl/flutter_corelibrary
description: Lint rules used at LeanCode.

topics:
  - analysis
  - lints

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  analyzer: ^6.1.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.0
