name: leancode_lint
version: 20.0.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_lint
repository: https://github.com/leancodepl/flutter_corelibrary
description: Robust, high-quality lint rules used at LeanCode.

topics:
  - analysis
  - lints

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  analysis_server_plugin: ^0.3.8
  analyzer: ^10.0.2
  analyzer_plugin: ^0.14.2
  meta: ^1.18.0
  path: ^1.9.1
  source_span: ^1.10.1
  yaml: ^3.1.3

dev_dependencies:
  analyzer_testing: ^0.1.10
  test_reflective_loader: ^0.4.0
