name: leancode_hooks
version: 0.1.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_hooks
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  Hooks we often use, all gathered in one place.

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0 <4.0.0"

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5

dev_dependencies:
  coverage: ^1.2.0
  custom_lint: ">=0.6.4 <0.8.0"
  flutter_test:
    sdk: flutter
  leancode_lint: ">=12.0.0 <15.0.0"
