name: leancode_hooks
version: 0.0.3
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_hooks
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  Hooks we often use, all gathered in one place.

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0 <3.0.0'

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.3

dev_dependencies:
  coverage: ^1.2.0
  flutter_test:
    sdk: flutter
  leancode_lint: ^1.1.0
