name: override_api_endpoint
version: 1.0.0+3
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/override_api_endpoint
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  This package is prepared so that backend developers can override api endpoint
  for some local one without the need to compile the app. The desired behavior is
  realized with deeplinks. The override URL is persisted until a new deeplink
  is used.

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  shared_preferences: ^2.0.6

dev_dependencies:
  leancode_lint: 3.0.0
