name: leancode_force_update
version: 1.0.0-alpha
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_force_update
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  An internal package that speeds up implementation of Force Update
  
environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  cqrs: ^10.0.1
  flutter:
    sdk: flutter
  in_app_update: ^4.1.4
  leancode_contracts: ^0.8.0
  logging: ^1.2.0 
  package_info_plus: ">=4.0.2 <9.0.0"
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12
  version: ^3.0.2

dev_dependencies:
  flutter_lints: ">=2.0.0 <6.0.0"
  flutter_test:
    sdk: flutter
  leancode_contracts_generator: ">=0.11.0 <0.13.0"
  leancode_lint: ">=4.0.0+1 <16.0.0"
  mocktail: ">=0.3.0 <2.0.0"
