name: cqrs
version: 10.0.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/cqrs
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A library for convenient communication with CQRS-compatible backends, using
  queries and commands.

environment:
  sdk: '>=3.0.1 <4.0.0'

dependencies:
  equatable: ^2.0.5
  http: ^1.0.0
  logging: ^1.2.0

dev_dependencies:
  coverage: ^1.5.0
  leancode_lint: ">=4.0.0+1 <7.0.0"
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.17.5
