name: cqrs
version: 6.2.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/cqrs
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A library for convenient communication with CQRS-compatible backends, using
  queries and commands.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^0.13.3

dev_dependencies:
  build_runner: ^2.0.4
  coverage: ^1.0.3
  leancode_lint: 1.0.2
  mockito: ^5.0.9
  test: ^1.17.5
