name: cqrs
version: 5.0.1-nullsafety.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/cqrs
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  A library for convenient communication with CQRS-compatible backends, using
  queries and commands.

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  http: ^0.13.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.10.13
  lint: ^1.5.1
  mockito: ^5.0.0-nullsafety.4
  test: ^1.16.0-nullsafety.13
  test_coverage: ^0.5.0
