name: leancode_analytics
description: Package provides wrapper for base analytics functionality for Flutter apps.
version: 0.2.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_analytics
repository: https://github.com/leancodepl/flutter_corelibrary

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  firebase_analytics: ^11.4.5
  firebase_core: ^3.13.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ">=14.0.0 <16.0.0"
