name: leancode_analytics
description: A new Flutter package project.
version: 0.0.2
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_analytics: ^10.4.3
  firebase_core: ^2.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ">=6.0.0 <8.0.0"

flutter:

