name: leancode_analytics
description: Package provides wrapper for base analytics functionality for Flutter apps.
version: 0.0.2
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/leancode_analytics
repository: https://github.com/leancodepl/flutter_corelibrary

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  firebase_analytics: ">=10.4.3 <12.0.0"
  firebase_core: ">=2.1.1 <4.0.0"
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ">=0.5.6 <0.7.0"
  flutter_test:
    sdk: flutter
  leancode_lint: ">=8.0.0 <15.0.0"
