name: login_client_flutter
version: 1.0.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client_flutter
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  OAuth2 compliant login client that stores credentials
  for the currently authenticated user and automatically
  refreshes tokens. // todo

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: '>=1.22.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.5
  login_client:
    path: ../login_client
  oauth2: ^1.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  mockito: ^4.1.3
