name: login_client_flutter
version: 1.0.1
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client_flutter
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  flutter_secure_storage implementation of a CredentialsStorage
  for the login_client package.

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.24.0-0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^3.3.5
  login_client: ^1.0.0
  oauth2: ^1.6.3

dev_dependencies:
  lint: ^1.3.0
