name: login_client_flutter
version: 3.0.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client_flutter
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  flutter_secure_storage implementation of a CredentialsStorage
  for the login_client package.

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: '>=4.2.0 <6.0.0'
  login_client: ^3.0.0

dev_dependencies:
  custom_lint: ^0.5.6
  leancode_lint: ^8.0.0
