name: login_client_flutter
version: 2.1.0
homepage: https://github.com/leancodepl/flutter_corelibrary/tree/master/packages/login_client_flutter
repository: https://github.com/leancodepl/flutter_corelibrary
description: >-
  flutter_secure_storage implementation of a CredentialsStorage
  for the login_client package.

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^4.2.0
  login_client: ^2.0.1

dev_dependencies:
  lint: ^1.5.3
